-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: 41e26ab636aab10b8b367c9654d606604c0e5da8
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 1be8707dc71dbaed8e0b2cb72bfe83a604183a92
    hooks:
    -   id: flake8
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    rev: 96209e0f210e2cb8b87dfecb19ce4066bad75cb6
    hooks:
    -   id: scss-lint
